import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

// Le terme children est un terme réservé
export default function Layout({ title, currentPage, children }) {
  return (
    <div className="flex flex-col w-screen min-h-screen bg-gray-200 pt-8 px-8">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex items-center w-full shadow-md mb-8 px-8 py-6">
        {/* N'est pas une balise image mais un component pour optimiser les images */}
        <Image src="/cat.png" alt="Chat noir" width={100} height={100} />
        <nav className="ml-8 ">
          <ul className="flex">
            <li className="mr-6">
              <Link
                href="/"
                className={`text-indigo-600 ${
                  currentPage === "home" && "font-semibold"
                }`}
              >
                Accueil
              </Link>
            </li>
            <li className="mr-6">
              <Link
                href="/todos"
                className={`text-indigo-600 ${
                  currentPage === "todos" && "font-semibold"
                }`}
              >
                Todos
              </Link>
            </li>
          </ul>
        </nav>
      </header>
      <main className="container p-8 mx-auto">{children}</main>
    </div>
  );
}
